Minor code fixes/updates
boringproxy/boringproxy pull request #170
Opened 2022-02-25 06:36 UTC by WGrobler

Changes:

- PrintLogin was showing first token and not checking if its a client token
- PrintLogin not showing correct port (not often used, but bug nonetheless)
- Added open in new tab for domains in Web UI tunnels

2022-02-25 18:08 UTC, anderspitman requested changes

2022-02-25 18:08 UTC, anderspitman commented on templates/tunnels.tmpl
> +          <a href='https://{{$domain}}' target="_blank">{{$domain}}</a>
I would prefer to leave these as standard links. You should inform the user if a link is going to open a new tab/window, and I'd prefer not to clutter the UI with that information. You can always right-click or long-press to open in a tab.

2022-02-27 05:57 UTC, WGrobler commented on templates/tunnels.tmpl
> +          <a href='https://{{$domain}}' target="_blank">{{$domain}}</a>
For normal web pages I would agree, but when it comes to admin portals, opening links to hosted services/websites should be opened in new tabs. Navigating away from the admin portal while leaving the session open is a security risk. Furthermore, these types of links are mostly used for testing when the user is busy working in their admin portal, when a user want to open the links for everyday use they should open the relevant website directly and not navigate via the admin portal.

I had a quick look at [cPanel](https://cpanel.net/), their systems are not perfect, but they are a leader in making tools for entry level hosting solutions. Their web UI on the WHM (web host manager) side shows links to all the domains linked to the account, similar to how boringproxy displays tunnels. When clicking on any of the links the page is opened in a new tab. Also there is no indication that the page will open in a new link. 

The same can be found in [runcloud.io](https://runcloud.io/) and [www.ispconfig.org](https://www.ispconfig.org/), from my quick check I could not find an admin portal that has links to hosted websites that open the links in the same tab.

2022-03-01 22:41 UTC, anderspitman commented on templates/tunnels.tmpl
> +          <a href='https://{{$domain}}' target="_blank">{{$domain}}</a>
Fair enough. I don't have strong feelings about this one.

2022-03-01 22:41 UTC, merged